name: optics_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"
  
dependencies:
  # optics_annotation: ^0.1.0
  optics_annotation: 
    path: ../optics_annotation
    
  build: ^2.0.0
  source_gen: ^1.0.0
  analyzer: '>=2.0.0 <6.0.0'

dev_dependencies:
  build_runner: ^2.0.0
  flutter_lints: ^2.0.0